name: Build and Test Jolt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cache Jolt RISC-V Rust toolchain
        uses: actions/cache@v4
        with:
          key: jolt-rust-toolchain-${{hashFiles('.jolt.rust.toolchain-tag')}}
          path: ~/.jolt
      - name: Install Jolt RISC-V Rust toolchain
        run: cargo run install-toolchain
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run jolt-core tests
        run: cargo nextest run -p jolt-core
